export default () => ({
  port: parseInt(process.env.PORT ?? '3000', 10),
  whatsappWabaId: process.env.WHATSAPP_WABA_ID,
  whatsappToken: process.env.WHATSAPP_TOKEN,
  whatsappPhoneId: process.env.WHATSAPP_PHONE_ID,
  whatsappverifyToken: process.env.WHATSAPP_VERIFY_TOKEN,
  MICROSOFT_APP_ID: process.env.MICROSOFT_APP_ID,
  MICROSOFT_APP_PASSWORD: process.env.MICROSOFT_APP_PASSWORD,
  MICROSOFT_APP_TENANT_ID: process.env.MICROSOFT_APP_TENANT_ID,
  teamsChannelId: process.env.TEAMS_CHANNEL_ID,
  teamsTeamId: process.env.TEAMS_TEAM_ID,
  teamsBotName: process.env.TEAMS_BOT_NAME ?? 'botito',
  publicUrl: process.env.PUBLIC_URL,
  // ClamAV (opcional): ENABLE_CLAMAV=true para escanear archivos
  ENABLE_CLAMAV: process.env.ENABLE_CLAMAV,
  CLAMAV_USE_DAEMON: process.env.CLAMAV_USE_DAEMON,
  CLAMAV_SOCKET: process.env.CLAMAV_SOCKET,
  CLAMAV_HOST: process.env.CLAMAV_HOST,
  CLAMAV_PORT: process.env.CLAMAV_PORT ? parseInt(process.env.CLAMAV_PORT, 10) : undefined,
  CLAMAV_PATH: process.env.CLAMAV_PATH,
  BUSINESS_HOURS_START: process.env.BUSINESS_HOURS_START,
  BUSINESS_HOURS_END: process.env.BUSINESS_HOURS_END,
  BUSINESS_DAYS: process.env.BUSINESS_DAYS,
  DB_HOST: process.env.DB_HOST,
  DB_PORT: process.env.DB_PORT,
  DB_USER: process.env.DB_USER,
  DB_PASSWORD: process.env.DB_PASSWORD,
  DB_NAME: process.env.DB_NAME,
  ubersmith: {
    apiUrl: process.env.UBERSMITH_API_URL,
    apiUser: process.env.UBERSMITH_API_USER,
    apiPass: process.env.UBERSMITH_API_PASS,
  },
});
